fix probrems

diff --git a/nginx/certmgr b/nginx/certmgr
--- a/nginx/certmgr
+++ b/nginx/certmgr
@@ -3,27 +3,37 @@ CONF="/etc/samba/smb-user.conf"
 
 subj="/C=JP/CN=client"
 p12_pass=""
-output_dir="/V/cert"
-input_dir=$CERT_DIR
+output_dir="/V/cert/gen"
+ca_dir=/V/cert
 name="certmgr"
 days=365
+index_flag=""
 
-create_key() {
+_setup_ca() {
 
-    while getopts ":s:p:i:o:n:d:h" OPT;do
+    if [ ! -d "$1/demoCA" ]; then
+        mkdir -p "$1/demoCA/newcerts"
+        touch "$1/demoCA/index.txt"
+        echo 1000 > "$1/demoCA/crlnumber"
+        echo 1000 > "$1/demoCA/serial"  
+    fi
+}
+
+create() {
+
+    while getopts ":p:c:o:s:n:d:h" OPT;do
         case $OPT in
-            s)  subj=$OPTARG;;
             p)  p12_pass=$OPTARG;;
-            i)  input_dir=$OPTARG;;
+            c)  ca_dir=$OPTARG;;
             o)  output_dir=$OPTARG;;
+            s)  subj=$OPTARG;;
             n)  name=$OPTARG;;
             d)  days=$OPTARG;;
             h)  echo "Usage: $0 -k <key_path> [-h]"
-                echo "  -k <key_path> : Path to save the generated key"
-                echo "  -s <subject>  : Subject for the certificate (default: /C=JP/CN=client)"
                 echo "  -p <password> : Password for the PKCS#12 file"
-                echo "  -i <input_dir>: Input directory for CA files (default: $CERT_DIR)"
+                echo "  -c <ca_dir>   : Input directory for CA files (default: $CERT_DIR)"
                 echo "  -o <output_dir>: Output directory for generated files (default: /V/cert)"
+                echo "  -s <subject>  : Subject for the certificate (default: /C=JP/CN=client)"
                 echo "  -n <name>     : Base name for the generated files (default: certmgr)"
                 echo "  -d <days>     : Validity period in days (default: 365)"
                 echo "  -h            : Show this help message"
@@ -38,11 +48,49 @@ create_key() {
         exit 1
     fi
 
+    if [ ! -s "$ca_dir/ca.crt" ] || [ ! -s "$ca_dir/ca.key" ]; then
+        echo "CA files not found in $ca_dir"
+        exit 1
+    elif [ -s "$output_dir/$name.crt" ] || [ -s "$output_dir/$name.p12" ]; then
+        echo "Output files already exist in $output_dir"
+        exit 1
+    fi
+
     mkdir -p $output_dir
-    
+    _setup_ca $ca_dir
+    cd $ca_dir
     openssl req -noenc -newkey ec -pkeyopt ec_paramgen_curve:secp384r1 -keyout $output_dir/$name.key -out $output_dir/$name.csr -subj $subj
-    openssl x509 -req -CA $input_dir/ca.crt -CAkey $input_dir/ca.key -in $output_dir/$name.csr -out $output_dir/$name.crt -days $days -sha256
-    openssl pkcs12 -export -inkey $output_dir/$name.key -in $output_dir/$name.crt -certfile $input_dir/ca.crt -out $output_dir/$name.p12 -passout pass:$p12_pass
+    openssl ca -batch -quiet -cert $ca_dir/ca.crt -keyfile $ca_dir/ca.key -in $output_dir/$name.csr -out $output_dir/$name.crt -days $days
+    openssl pkcs12 -export -inkey $output_dir/$name.key -in $output_dir/$name.crt -certfile $ca_dir/ca.crt -out $output_dir/$name.p12 -passout pass:$p12_pass
+
+}
+
+revoke() {
+
+    while getopts ":i:c:n:h" OPT;do
+        case $OPT in
+            c)  ca_dir=$OPTARG;;
+            i)  input_dir=$OPTARG;;
+            n)  name=$OPTARG;;
+            h)  echo "Usage: $0 -c <ca_dir> -i <input_dir> [-h]"
+                echo "  -i <input_dir>: Certificate absolute path to revoke"
+                echo "  -c <ca_dir>   : CA directory containing ca.crt and ca.key (default: $CERT_DIR)"
+                echo "  -h            : Show this help message"
+                exit 0;;
+            *) echo "option Error: $OPT is not a valid option"
+            exit;;
+        esac
+    done
+
+    if [ -z "$input_dir" ]; then
+        echo "password is required"
+        exit 1
+    fi
+    
+    _setup_ca $ca_dir
+    cd $ca_dir
+    openssl ca -keyfile $ca_dir/ca.key -cert $ca_dir/ca.crt -revoke $input_dir/$name.crt
+    openssl ca -gencrl -keyfile $ca_dir/ca.key -cert $ca_dir/ca.crt -out $ca_dir/crl.pem
 
 }
 
@@ -56,7 +104,11 @@ case $1 in
         ;;
     create)
         shift
-        create_key "$@"
+        create "$@"
+        ;;
+    revoke)
+        shift
+        revoke "$@"
         ;;
     *)
         echo "Invalid option. Use 'help' for usage information."
